import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import NavBar from '@/components/NavBar'

export const runtime = 'edge'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Natanon BBL Test',
  description: 'Generated by Natanon',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-light w-full h-[100dvh] min-h-screen">
        <NavBar />
        {children}
      </body>
    </html>
  )
}
